name: Release Prebuilt Binaries

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------------
      # Install dependencies
      # ------------------------------
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      - name: Setup Xcode (macOS)
        if: matrix.os == 'macos-latest'
        run: sudo xcode-select --install || true

      - name: Setup MSVC (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-msbuild@v1

      # ------------------------------
      # Configure & build
      # ------------------------------
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      # ------------------------------
      # Package Linux
      # ------------------------------
      - name: Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p release
          cp build/cpp-scaffolder release/
          tar -czf cpp-scaffolder-v${{ github.ref_name }}-linux.tar.gz -C release cpp-scaffolder

      # ------------------------------
      # Package macOS
      # ------------------------------
      - name: Package macOS
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p release
          cp build/cpp-scaffolder release/
          tar -czf cpp-scaffolder-v${{ github.ref_name }}-macos.tar.gz -C release cpp-scaffolder

      # ------------------------------
      # Package Windows
      # ------------------------------
      - name: Package Windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          mkdir release
          Copy-Item -Path "build/Release/cpp-scaffolder.exe" -Destination "release/"
          Compress-Archive -Path "release/cpp-scaffolder.exe" -DestinationPath "cpp-scaffolder-v${{ github.ref_name }}-windows.zip"

      # ------------------------------
      # Upload Release Assets
      # ------------------------------
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cpp-scaffolder-v${{ github.ref_name }}-linux.tar.gz
            cpp-scaffolder-v${{ github.ref_name }}-macos.tar.gz
            cpp-scaffolder-v${{ github.ref_name }}-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
